-- INSERT INTO COMMUNITY
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Enterprise .NET Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Full-stack Web Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Quality Engineering Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Cloud and DevOps Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Big Data & Analytics Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Product Delivery Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Enterprise Coffee Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Mobile Community', true, 0);
INSERT INTO public.community (communityname, isactive, communitymgrid) VALUES('Research and Development Community(new)', true, 0);

-- INSERT INTO JOBLEVEL
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Community Director', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Community Manager', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Regional Solutions Architect', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Solutions Architect', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Principal Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Lead Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Associate Lead Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Senior Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Undefined', TRUE);

-- INSERT INTO PEOPLE
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943094, 'Navaja', 'Buboy', 'S', 'Buboy Navaja', 'florante.navaja@softvision.com', '2019-06-01', 7, 7, 2, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946847, 'Tuazon', 'Mau', 'S', 'Mau Tuazon', 'mauriza.tuazon@softvision.com', '2017-09-23', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946585, 'Flores', 'Bob', 'S', 'Bob Flores', 'ronyan.flores@softvision.com', '2020-01-19', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941650, 'De Los Angeles', 'Wayne', 'S', 'Wayne De Los Angeles', 'wayne.delosangeles@softvision.com', '2017-10-18', 7, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949150, 'Rueda', 'Paolo', 'S', 'Paolo Rueda', 'paolorey.rueda@softvision.com', '2019-07-15', 7, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945456, 'Castro', 'Allan', 'S', 'Allan Castro', 'allan.castro2@softvision.com', '2020-12-25', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944821, 'Dableo', 'Arnold', 'S', 'Arnold Dableo', 'arnold.dableo@softvision.com', '2019-07-10', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943573, 'Natividad', 'Aura', 'S', 'Aura Natividad', 'auracedes.natividad@softvision.com', '2021-06-01', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945770, 'Vergara', 'Christian', 'S', 'Christian Vergara', 'christianpaul.vergara@softvision.com', '2017-11-01', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949537, 'Macatangay', 'Eldrich', 'S', 'Eldrich Macatangay', 'eldrich.macatangay@softvision.com', '2017-08-29', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941254, 'Dela Peña', 'Hanami', 'S', 'Hanami Dela Peña', 'hanamiann.delapena@softvision.com', '2021-05-01', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944269, 'Tandang', 'Jan Aldrich', 'S', 'Jan Aldrich Tandang', 'janaldrich.tandang@softvision.com', '2021-09-12', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945572, 'Vallejos', 'Jayhar', 'S', 'Jayhar Vallejos', 'jayhar.vallejos@softvision.com', '2019-12-17', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943985, 'Silvestre', 'Jerome', 'S', 'Jerome Silvestre', 'jerome.silvestre@softvision.com', '2021-04-11', 7, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950779, 'Corpuz', 'Jim', 'S', 'Jim Corpuz', 'janianmichael.corpuz@softvision.com', '2020-11-02', 7, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947194, 'Balbarona', 'Jojo', 'S', 'Jojo Balbarona', 'jojo.balbarona@softvision.com', '2018-01-14', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950564, 'Serrano', 'Joseph', 'S', 'Joseph Serrano', 'josephdavid.serrano@softvision.com', '2017-05-07', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941226, 'Gloria', 'Josha', 'S', 'Josha Gloria', 'joshuamiguel.gloria@softvision.com', '2019-07-11', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948687, 'Boado', 'Justin', 'S', 'Justin Boado', 'justinbernard.boado@softvision.com', '2017-06-28', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950067, 'Cautiverio', 'Loyd', 'S', 'Loyd Cautiverio', 'loydzedric.cautiverio@softvision.com', '2017-06-07', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944190, 'Peñano', 'Marc', 'S', 'Marc Peñano', 'marcdominic.penano@softvision.com', '2021-04-25', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949082, 'Obog', 'Mario', 'S', 'Mario Obog', 'marionino.obog@softvision.com', '2020-04-07', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949845, 'Abrazado', 'Nikko', 'S', 'Nikko Abrazado', 'nikkopaulo.abrazado@softvision.com', '2017-10-27', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948694, 'Cayetano', 'Niño', 'S', 'Niño Cayetano', 'ninobenedict.cayetano@softvision.com', '2017-03-10', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948172, 'Daza', 'Olive', 'S', 'Olive Daza', 'olive.daza@softvision.com', '2017-09-15', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942683, 'Eliseo', 'Pauline', 'S', 'Pauline Eliseo', 'paulinejoena.eliseo@softvision.com', '2019-02-20', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943824, 'Maquinto', 'Jan Philipp', 'S', 'Jan Philipp Maquinto', 'janphilipp.maquinto@softvision.com', '2018-09-25', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945106, 'Lipardo', 'Roi', 'S', 'Roi Lipardo', 'roijesson.lipardo@softvision.com', '2018-10-09', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941722, 'Orobia', 'Runette', 'S', 'Runette Orobia', 'runettenicole.orobia@softvision.com', '2020-12-30', 7, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946546, 'Gonzales', 'Warren', 'S', 'Warren Gonzales', 'warren.gonzales@softvision.com', '2017-10-10', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945010, 'Decena', 'Zaldy', 'S', 'Zaldy Decena', 'rizaldy.decena@softvision.com', '2017-11-10', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945720, 'Gonzales', 'Alvin', 'S', 'Alvin Gonzales', 'alvin.gonzales@softvision.com', '2020-10-01', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945255, 'Evangelista', 'Miah', 'S', 'Miah Evangelista', 'jeremiah.evangelista@softvision.com', '2018-12-31', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948390, 'Mantaring', 'Rod', 'S', 'Rod Mantaring', 'jamesrod.mantaring@softvision.com', '2021-05-26', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949745, 'Gomez', 'Jerymy', 'S', 'Jerymy Gomez', 'jerymy.gomez@softvision.com', '2017-12-10', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943583, 'Suan', 'Jayson', 'S', 'Jayson Suan', 'jayson.suan@softvision.com', '2020-04-22', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946971, 'Hagos', 'Stevania', 'S', 'Stevania Hagos', 'stevaniaallison.h@softvision.com', '2019-04-29', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944043, 'Perez', 'Christian', 'S', 'Christian Perez', 'christian.perez@softvision.com', '2020-03-22', 7, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949410, 'Macandili', 'Aaron', 'S', 'Aaron Macandili', 'aaron.macandili@softvision.com', '2021-10-18', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946312, 'Alcachupas', 'Charles', 'S', 'Charles Alcachupas', 'charles.alcachupas@softvision.com', '2019-04-14', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950796, 'Felix', 'Tonette', 'S', 'Tonette Felix', 'mariaantoinette.f@softvision.com', '2017-06-13', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946896, 'Villanueva', 'Jophiel', 'S', 'Jophiel Villanueva', 'jophiel.villanueva@softvision.com', '2021-03-30', 7, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944938, 'Morales', 'John', 'S', 'John Morales', 'john.morales@softvision.com', '2020-02-04', 7, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945716, 'Mariano', 'Jhan Jerico', 'S', 'Jhan Jerico Mariano', 'jhanjericho.mariano@softvision.com', '2017-03-26', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945610, 'Dela Cruz', 'Rozen', 'S', 'Rozen Dela Cruz', 'rozen.delacruz@softvision.com', '2018-12-30', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948133, 'Escaro', 'Kevin', 'S', 'Kevin Escaro', 'kevin.escaro@softvision.com', '2017-11-30', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947174, 'Estrada', 'Gerald', 'S', 'Gerald Estrada', 'gerald.estrada@softvision.com', '2021-04-02', 7, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947044, 'Catipon', 'Mary Allen', 'S', 'Mary Allen Catipon', 'allen.catipon@softvision.com', '2021-09-11', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942111, 'Dela Cruz', 'Michael', 'S', 'Michael Dela Cruz', 'michael.delacruz@softvision.com', '2021-02-03', 7, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947980, 'Gealogo', 'Joemar', 'S', 'Joemar Gealogo', 'joemar.gealogo@softvision.com', '2017-09-07', 7, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949184, 'Limosenero', 'Rey', 'S', 'Rey Limosenero', 'rey.limosenero@softvision.com', '2017-09-10', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947409, 'Grezola', 'Reyzald', 'S', 'Reyzald Grezola', 'reyzald.grezola@softvision.com', '2019-04-09', 7, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944153, 'Legaspi', 'Mary Allen', 'S', 'Mary Allen Legaspi', 'maryanne.legaspi@softvision.com', '2018-10-01', 7, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942088, 'Dela Torre', 'Joseph', 'S', 'Joseph Dela Torre', 'joseph.delatorre@softvision.com', '2019-03-15', 7, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947174, 'Celis', 'Dax', 'S', 'Dax Celis', 'daxgabriel.celis@softvision.com', '2020-05-30', 8, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942642, 'Cruz', 'Lyndon', 'S', 'Lyndon Cruz', 'lyndon.cruz@softvision.com', '2019-03-26', 8, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949563, 'Cariaga', 'Hermoso', 'S', 'Hermoso Cariaga', 'hermoso.cariaga@softvision.com', '2018-03-30', 8, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941473, 'Tayabas', 'Anthony', 'S', 'Anthony Tayabas', 'anthonymark.tayabas@softvision.com', '2021-09-06', 8, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948018, 'Castro', 'Allan ', 'S', 'Allan  Castro', 'allan.castro2@softvision.com', '2017-02-03', 8, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948905, 'Villaflor', 'Mac Mac', 'S', 'Mac Mac Villaflor', 'markjoseph.villaflor@softvision.com', '2017-09-27', 8, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941360, 'Sarmiento', 'Michael', 'S', 'Michael Sarmiento', 'michael.sarmiento@softvision.com', '2019-05-18', 8, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947318, 'Mosca', 'Neil', 'S', 'Neil Mosca', 'neilnicoli.mosca@softvision.com', '2021-02-05', 8, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945262, 'Muñoz', 'Rica', 'S', 'Rica Muñoz', 'rica.munoz@softvision.com', '2020-01-04', 8, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948860, 'Ulep', 'Robert', 'S', 'Robert Ulep', 'robert.ulep@softvision.com', '2020-09-20', 8, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943916, 'Roman', 'Tobby', 'S', 'Tobby Roman', 'tobyrodin.roman@softvision.com', '2019-08-23', 8, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950700, 'Clemente', 'Faye', 'S', 'Faye Clemente', 'cecilfaye.clemente@softvision.com', '2020-09-12', 8, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941032, 'Tuazon', 'Harvy', 'S', 'Harvy Tuazon', 'harvy.tuazon@softvision.com', '2020-12-05', 8, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941444, 'Bocobo', 'Rhoderick', 'S', 'Rhoderick Bocobo', 'rhoderick.bocobo@softvision.com', '2020-09-02', 8, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946232, 'Aguado', 'John Joseph', 'S', 'John Joseph Aguado', 'johnjoseph.aguado@softvision.com', '2020-11-11', 8, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942230, 'Dela Rosa', 'Gian', 'S', 'Gian Dela Rosa', 'gianroni.delarosa@softvision.com', '2019-04-06', 8, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944018, 'Dumagat', 'Johnny', 'S', 'Johnny Dumagat', 'johnny.dumagat@softvision.com', '2019-07-05', 8, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943407, 'Flores', 'Randy', 'S', 'Randy Flores', 'randy.flores@softvision.com', '2020-08-17', 8, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946788, 'Villegas', 'Douie Villegas', 'S', 'Douie Villegas Villegas', 'douienino.villegas@softvision.com', '2018-02-28', 4, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949747, 'Barrientos', 'Elther Barrientos', 'S', 'Elther Barrientos Barrientos', 'elther.barrientos@softvision.com', '2019-07-09', 4, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945463, 'Sunpongco II', 'Herminigildo', 'S', 'Herminigildo Sunpongco II', 'herminigildo.sunpongco@softvision.com', '2020-11-18', 4, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950303, 'Acido', 'Jayveelyn', 'S', 'Jayveelyn Acido', 'jayveelyn.acido@softvision.com', '2020-01-11', 4, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944687, 'Gallego', 'John Kenneth', 'S', 'John Kenneth Gallego', 'johnkenneth.gallego@softvision.com', '2017-07-19', 4, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945981, 'Miguel', 'Lloyd Joseph', 'S', 'Lloyd Joseph Miguel', 'lloydjoseph.miguel@softvision.com', '2020-01-26', 4, 7, 2, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946283, 'Matela', 'Lorenzo Alexander', 'S', 'Lorenzo Alexander Matela', 'lorenzoalexander.matela@softvision.com', '2021-01-22', 4, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943158, 'Budy', 'Maryjoy', 'S', 'Maryjoy Budy', 'maryjoy.budy@softvision.com', '2017-02-27', 4, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949150, 'Manalo', 'Michael', 'S', 'Michael Manalo', 'michael.manalo@softvision.com', '2019-11-02', 4, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949900, 'Tapon', 'Paul Evangel', 'S', 'Paul Evangel Tapon', 'paulevangel.tapon@softvision.com', '2021-05-03', 4, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945429, 'Gollayan', 'Raffie', 'S', 'Raffie Gollayan', 'raffie.gollayan@softvision.com', '2017-01-21', 4, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947092, 'Hernandez', 'Ron', 'S', 'Ron Hernandez', 'ron.hernandez@softvision.com', '2018-12-15', 4, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944458, 'Borlongan', 'Ted', 'S', 'Ted Borlongan', 'ted.borlongan@softvision.com', '2017-11-16', 4, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947724, 'Uy', 'Tyrone Rodney', 'S', 'Tyrone Rodney Uy', 'tyronerodney.uy@softvision.com', '2017-05-08', 4, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944750, 'Zabala', 'Zackary', 'S', 'Zackary Zabala', 'zackary.zabala@softvision.com', '2019-07-17', 4, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942603, 'Macapagal', 'Aaron', 'S', 'Aaron Macapagal', '', '2021-04-08', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950792, 'Carandang Jr', 'Alberto', 'S', 'Alberto Carandang Jr', '', '2018-09-16', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947312, 'Salaño', 'Alfie', 'S', 'Alfie Salaño', '', '2018-11-13', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941136, 'Pajaret', 'Alfredo James', 'S', 'Alfredo James Pajaret', '', '2020-08-06', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941223, 'Cadiz', 'Aljon Rey', 'S', 'Aljon Rey Cadiz', '', '2019-10-01', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942416, 'Tolentino', 'Allan', 'S', 'Allan Tolentino', '', '2018-12-13', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942770, 'Lopez', 'Allan', 'S', 'Allan Lopez', '', '2020-07-02', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942696, 'Tolentino', 'Alter', 'S', 'Alter Tolentino', '', '2017-02-28', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945099, 'Espinosa', 'Alvin', 'S', 'Alvin Espinosa', '', '2018-08-10', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945143, 'Santelices', 'Andrew', 'S', 'Andrew Santelices', '', '2017-06-11', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948815, 'Manalili', 'Angelo', 'S', 'Angelo Manalili', '', '2017-09-07', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948910, 'Herana', 'Angelo', 'S', 'Angelo Herana', '', '2019-07-13', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946644, 'Anonas', 'Anthony', 'S', 'Anthony Anonas', '', '2021-02-09', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943664, 'Lopez', 'Armando', 'S', 'Armando Lopez', '', '2020-04-14', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948724, 'Parulan', 'Benedick', 'S', 'Benedick Parulan', '', '2018-10-29', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950175, 'Buluran', 'Benjamin', 'S', 'Benjamin Buluran', '', '2021-07-06', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949648, 'Manalo', 'Benjie', 'S', 'Benjie Manalo', '', '2017-03-02', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949837, 'Berns', 'Caay', 'S', 'Caay Berns', '', '2019-01-24', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945973, 'Yap', 'Angela Bianca', 'S', 'Angela Bianca Yap', '', '2018-12-30', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947847, 'Ogerio', 'Bien Liomar', 'S', 'Bien Liomar Ogerio', '', '2019-05-30', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947492, 'Guevarra', 'Benjo', 'S', 'Benjo Guevarra', '', '2017-04-11', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948391, 'Malbataan', 'Billy', 'S', 'Billy Malbataan', '', '2021-09-18', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944072, 'Tiamsic', 'Bob', 'S', 'Bob Tiamsic', '', '2017-07-02', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942713, 'Baldos', 'Brian', 'S', 'Brian Baldos', '', '2018-05-04', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950562, 'Arabejo', 'Bryan', 'S', 'Bryan Arabejo', '', '2018-09-22', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941443, 'Feliciano', 'Bryantt', 'S', 'Bryantt Feliciano', '', '2021-04-09', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943518, 'Cerbo', 'Chen', 'S', 'Chen Cerbo', '', '2019-07-25', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949841, 'Abejuro', 'Christian', 'S', 'Christian Abejuro', '', '2021-02-13', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948873, 'Sarzaba', 'Christian', 'S', 'Christian Sarzaba', '', '2017-09-22', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948096, 'Palisoc', 'Christopher', 'S', 'Christopher Palisoc', '', '2018-03-13', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950625, 'Tubig', 'Christopher', 'S', 'Christopher Tubig', '', '2018-05-23', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944057, 'Ferrolino', 'Clyde Bryan', 'S', 'Clyde Bryan Ferrolino', '', '2020-04-07', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947810, 'Zamoranos', 'Coleen Ann', 'S', 'Coleen Ann Zamoranos', '', '2020-02-15', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944293, 'Dela Cuz', 'Denzel Eriz', 'S', 'Denzel Eriz Dela Cuz', '', '2017-05-30', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948866, 'Valderama', 'Derick', 'S', 'Derick Valderama', 'derrick.valderama@softvision.com', '2021-06-10', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945890, 'Aguirre', 'Edsel', 'S', 'Edsel Aguirre', '', '2019-05-23', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944201, 'Bayno', 'Edu', 'S', 'Edu Bayno', '', '2019-07-03', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949608, 'Edwin', 'Moncayo', 'S', 'Moncayo Edwin', '', '2020-03-06', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949343, 'Torres', 'Emmanuel Andrew', 'S', 'Emmanuel Andrew Torres', '', '2018-08-22', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942079, 'Caraan', 'Eric', 'S', 'Eric Caraan', '', '2017-05-03', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942438, 'Cariño', 'Erich', 'S', 'Erich Cariño', '', '2018-01-15', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944970, 'Emmanuel', 'Erin', 'S', 'Erin Emmanuel', '', '2017-09-19', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942894, 'Lirazan', 'Erwin', 'S', 'Erwin Lirazan', '', '2019-03-11', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941674, 'Reyes III', 'Rex', 'S', 'Rex Reyes III', '', '2019-02-05', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944294, 'De Guzman', 'Fernando', 'S', 'Fernando De Guzman', '', '2017-03-13', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945682, 'Jon', 'Yago', 'S', 'Yago Jon', '', '2019-06-05', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945809, 'Tacata', 'Francis', 'S', 'Francis Tacata', '', '2018-11-29', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947329, 'Sandico', 'Bullet', 'S', 'Bullet Sandico', '', '2017-05-28', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947440, 'Ala', 'Francis', 'S', 'Francis Ala', '', '2018-12-16', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949570, 'Compañado', 'Franklin', 'S', 'Franklin Compañado', '', '2021-05-10', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949569, 'Calica', 'Gabriel Angelo', 'S', 'Gabriel Angelo Calica', '', '2020-09-08', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948660, 'Ceredon', 'Gen', 'S', 'Gen Ceredon', '', '2018-01-07', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941878, 'Gono', 'Gerald', 'S', 'Gerald Gono', '', '2019-09-03', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947140, 'Bragais', 'Bimz', 'S', 'Bimz Bragais', '', '2020-02-18', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948625, 'Salaritan', 'Gian', 'S', 'Gian Salaritan', '', '2018-12-17', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943094, 'Daria', 'Giancarlo', 'S', 'Giancarlo Daria', '', '2017-06-08', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944983, 'Capiral', 'Hans Gustaf', 'S', 'Hans Gustaf Capiral', '', '2021-01-15', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946522, 'Oliver', 'Herbert', 'S', 'Herbert Oliver', 'herbert.oliver@softvision.com', '2021-08-31', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945482, 'Amaro', 'Herman', 'S', 'Herman Amaro', '', '2018-04-22', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943324, 'Alcaraz', 'James', 'S', 'James Alcaraz', '', '2017-07-13', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950867, 'Cusi', 'James Philip', 'S', 'James Philip Cusi', '', '2018-07-28', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948776, 'Carlos', 'JR', 'S', 'JR Carlos', '', '2017-10-22', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943782, 'Jan Mark', 'Bernales', 'S', 'Bernales Jan Mark', '', '2017-09-30', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941698, 'Paredes', 'Janniele', 'S', 'Janniele Paredes', '', '2019-06-03', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945374, 'Laguardia', 'Janzelle', 'S', 'Janzelle Laguardia', '', '2020-06-30', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944459, 'Cayetano', 'Jed', 'S', 'Jed Cayetano', '', '2021-02-28', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942353, 'Alfaro', 'Jefferson', 'S', 'Jefferson Alfaro', '', '2017-06-06', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948217, 'Acosta ', 'Jerffret', 'S', 'Jerffret Acosta ', 'jeffrey.acosta@softvision.com', '2018-05-06', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945422, 'Reverente', 'Jeffrey', 'S', 'Jeffrey Reverente', 'jeffreypaolo.reverente@softvision.com', '2020-04-22', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945451, 'Reyes', 'Jeffrey', 'S', 'Jeffrey Reyes', 'jesper.reyes@softvision.com', '2020-05-13', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946324, 'Castro', 'Jesse', 'S', 'Jesse Castro', '', '2020-02-25', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946291, 'Rykiel', 'Joel', 'S', 'Joel Rykiel', '', '2018-10-05', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945363, 'Banania', 'Joey', 'S', 'Joey Banania', '', '2021-01-02', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943993, 'Allen', 'John', 'S', 'John Allen', '', '2021-08-12', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947112, 'Decena', 'Dave', 'S', 'Dave Decena', '', '2019-08-14', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941901, 'Infante', 'Dave', 'S', 'Dave Infante', '', '2017-12-18', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941570, 'Tugado', 'John Ephraim', 'S', 'John Ephraim Tugado', 'johnephraim.tugado@softvision.com', '2017-05-24', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945529, 'Rimorin', 'John Jay', 'S', 'John Jay Rimorin', '', '2018-03-27', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941765, 'Go', 'Kevin', 'S', 'Kevin Go', '', '2018-02-17', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950451, 'Bersonda', 'John Patrick', 'S', 'John Patrick Bersonda', '', '2020-10-21', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945445, 'Lazaro', 'John Paul', 'S', 'John Paul Lazaro', 'johnpaul.lazaro@softvision.com', '2017-07-12', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941291, 'Ang', 'John Rafael', 'S', 'John Rafael Ang', '', '2018-04-01', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948018, 'Orale', 'John Raymer', 'S', 'John Raymer Orale', '', '2019-12-21', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946405, 'Malabanan', 'John Richard', 'S', 'John Richard Malabanan', 'johnrichard.malabanan@softvision.com', '2018-08-07', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941271, 'Taruc', 'Jommel', 'S', 'Jommel Taruc', '', '2019-06-05', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949003, 'Custodio', 'John Wendell', 'S', 'John Wendell Custodio', '', '2020-05-22', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947749, 'Jacob', 'Jonathan', 'S', 'Jonathan Jacob', '', '2021-01-15', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941005, 'Aguisanda', 'Jonnalyn', 'S', 'Jonnalyn Aguisanda', '', '2020-04-03', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946470, 'Molato', 'Jorelangelo', 'S', 'Jorelangelo Molato', 'jorelangelo.molato@softvision.com', '2021-06-28', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942580, 'Quipanes', 'Jose Marlon', 'S', 'Jose Marlon Quipanes', '', '2018-04-13', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945207, 'Manangan', 'Joseph', 'S', 'Joseph Manangan', 'joseph.manangan@softvision.com', '2021-03-20', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941797, 'Sanchez', 'Chard', 'S', 'Chard Sanchez', '', '2018-12-22', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950620, 'Tuazon', 'Joshua James', 'S', 'Joshua James Tuazon', '', '2020-09-21', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948958, 'Blanco', 'Jovan', 'S', 'Jovan Blanco', '', '2018-10-19', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942999, 'Roxas', 'Juan Gabriel', 'S', 'Juan Gabriel Roxas', '', '2017-02-18', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945616, 'De Castro', 'Julius Matthew', 'S', 'Julius Matthew De Castro', '', '2018-07-14', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945454, 'Belleza', 'Julius Miguel', 'S', 'Julius Miguel Belleza', '', '2017-01-04', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947802, 'Nicolas', 'Julius', 'S', 'Julius Nicolas', '', '2020-08-07', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941972, 'Montalban', 'Justin', 'S', 'Justin Montalban', '', '2020-09-09', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941453, 'Flamiano', 'Karen Dale', 'S', 'Karen Dale Flamiano', '', '2017-03-18', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942817, 'Lopez', 'Karenina', 'S', 'Karenina Lopez', '', '2019-10-26', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950894, 'Nuguid', 'Karen Mae', 'S', 'Karen Mae Nuguid', '', '2019-01-15', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944457, 'Canet', 'Kenneth', 'S', 'Kenneth Canet', 'kenneth.canet@softvision.com', '2020-02-19', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948029, 'Cainday', 'Kevin', 'S', 'Kevin Cainday', '', '2020-01-17', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947170, 'Vendiola', 'Kim', 'S', 'Kim Vendiola', '', '2020-10-04', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950342, 'Ramos', 'Kirstin Megga', 'S', 'Kirstin Megga Ramos', '', '2018-04-18', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948804, 'Cadalzo', 'Lambert', 'S', 'Lambert Cadalzo', '', '2020-08-03', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941947, 'Miguel', 'Lloyd', 'S', 'Lloyd Miguel', 'lloydjoseph.miguel@softvision.com', '2019-03-05', 1, 7, 2, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941190, 'Mabugay', 'Louie Gie', 'S', 'Louie Gie Mabugay', '', '2021-01-02', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947512, 'Estigoy', 'Marc Joemar', 'S', 'Marc Joemar Estigoy', '', '2021-07-09', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947440, 'Payong', 'Maria Theresa', 'S', 'Maria Theresa Payong', '', '2019-09-07', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946724, 'Sales', 'Mavie', 'S', 'Mavie Sales', '', '2020-04-02', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947439, 'Villanueva', 'Mark', 'S', 'Mark Villanueva', '', '2018-04-23', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948406, 'Nayat', 'Mark Anthony', 'S', 'Mark Anthony Nayat', '', '2017-01-28', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948072, 'Soriano', 'Mark Anthony', 'S', 'Mark Anthony Soriano', 'markanthony.soriano@softvision.com', '2017-03-02', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942864, 'Agrimano', 'Jerome', 'S', 'Jerome Agrimano', '', '2017-03-31', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941568, 'Ong', 'Lorenz', 'S', 'Lorenz Ong', '', '2018-05-13', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942558, 'Elpedes', 'Marlon', 'S', 'Marlon Elpedes', '', '2018-05-18', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943672, 'Briones', 'Marvin', 'S', 'Marvin Briones', '', '2021-03-13', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943912, 'Vicedo', 'Maxinne', 'S', 'Maxinne Vicedo', '', '2017-05-08', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948481, 'Hernanadex', 'Michael Ivan', 'S', 'Michael Ivan Hernanadex', 'michaelivan.hernandez@softvision.com', '2020-07-08', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946729, 'Vincent', 'Mikhail', 'S', 'Mikhail Vincent', '', '2017-01-24', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941736, 'Andre', 'Neil', 'S', 'Neil Andre', '', '2017-05-05', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941960, 'Solitana', 'Nico', 'S', 'Nico Solitana', '', '2017-05-15', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943137, 'Oriarte', 'Norben', 'S', 'Norben Oriarte', '', '2017-07-09', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945392, 'Ramos', 'Raymarc', 'S', 'Raymarc Ramos', '', '2017-09-19', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950844, 'Flores', 'Raymart', 'S', 'Raymart Flores', 'raymart.flores@softvision.com', '2021-04-06', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941387, 'De', 'Remar', 'S', 'Remar De', '', '2019-05-15', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943133, 'Rodriguez', 'Reycie', 'S', 'Reycie Rodriguez', '', '2021-07-20', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947244, 'Adonay', 'Reynner', 'S', 'Reynner Adonay', '', '2017-04-17', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947507, 'Bonion', 'Rhenier', 'S', 'Rhenier Bonion', '', '2019-08-20', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948389, 'Calingan', 'Jek', 'S', 'Jek Calingan', '', '2020-07-24', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943018, 'Jr.,', 'Rodrigo', 'S', 'Rodrigo Jr.,', '', '2019-01-28', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950077, 'John', 'Romel', 'S', 'Romel John', '', '2017-08-14', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941813, 'Alfred', 'Ron', 'S', 'Ron Alfred', '', '2017-01-04', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(944836, 'Osinsao', 'Rosemarie', 'S', 'Rosemarie Osinsao', '', '2020-06-25', 1, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945853, 'Rubin', 'Ryan', 'S', 'Ryan Rubin', '', '2019-12-27', 1, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949517, 'Aguilos', 'Samuel Marvin', 'S', 'Samuel Marvin Aguilos', '', '2021-06-26', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950937, 'Enriquez', 'Sean', 'S', 'Sean Enriquez', '', '2020-04-07', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943093, 'Buenaventura', 'Sidney', 'S', 'Sidney Buenaventura', '', '2017-05-09', 1, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947237, 'Malabonga', 'Ted Nico', 'S', 'Ted Nico Malabonga', 'TedNico.Malabonga@softvision.com', '2018-02-17', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946723, 'Paulo', 'Van', 'S', 'Van Paulo', '', '2018-07-22', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949976, 'Basco', 'Victorian', 'S', 'Victorian Basco', 'victorian.bascos@softvision.com', '2019-12-04', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945763, 'Wilfred', 'Dugang', 'S', 'Dugang Wilfred', '', '2017-10-30', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950537, 'Macatangay', 'Wilson', 'S', 'Wilson Macatangay', '', '2020-11-04', 1, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950966, 'Dela Rosa', 'Mark Jun D', 'S', 'Mark Jun D Dela Rosa', 'markjun.delarosa@softvision.com', '2021-03-14', 1, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(949406, 'Ursua Jr', 'Edgar', 'S', 'Edgar Ursua Jr', '', '2019-09-26', 1, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941546, 'Bonion', 'Rhenier', 'S', 'Rhenier Bonion', '', '2018-11-20', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946215, 'Richohermoso', 'Jerome', 'S', 'Jerome Richohermoso', '', '2018-10-17', 1, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946293, 'Valle', 'An Konim', 'S', 'An Konim Valle', 'ankonim.valle@softvision.com', '2018-02-01', 5, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942279, 'Bungabong', 'Anthony', 'S', 'Anthony Bungabong', 'anthony.bungabong@softvision.com', '2018-12-07', 5, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946132, 'Costales', 'Catherine Jean', 'S', 'Catherine Jean Costales', 'catherinejean.costales@softvision.com', '2019-03-09', 5, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947586, 'Tolete', 'Dustine', 'S', 'Dustine Tolete', 'dustine.tolete@softvision.com', '2017-11-26', 5, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942982, 'Balmonte', 'J Martin', 'S', 'J Martin Balmonte', 'jmartin.balmonte@softvision.com', '2017-10-22', 5, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(941754, 'Abello', 'John Dennis', 'S', 'John Dennis Abello', 'johndennis.abello@softvision.com', '2018-12-27', 5, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947359, 'Larida', 'John Paul', 'S', 'John Paul Larida', 'johnpaul.larida@softvision.com', '2018-07-18', 5, 7, 9, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942149, 'Capucion', 'Joyce Anne', 'S', 'Joyce Anne Capucion', 'joyceanne.capucion@softvision.com', '2019-08-28', 5, 7, 9, 2, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947978, 'Igrobay', 'Julie Pay', 'S', 'Julie Pay Igrobay', 'juliemae.igrobay@softvision.com', '2018-12-10', 5, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943614, 'Magsino', 'June Lester ', 'S', 'June Lester  Magsino', 'junellnino.magsino@softvision.com', '2018-06-15', 5, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946397, 'Ancisto', 'Lester', 'S', 'Lester Ancisto', 'lester.anciro@softvision.com', '2019-03-25', 5, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(943849, 'Miguel', 'Lloyd', 'S', 'Lloyd Miguel', 'lloydjoseph.miguel@softvision.com', '2020-02-23', 5, 7, 2, 4, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947503, 'Jacildone', 'Marilou', 'S', 'Marilou Jacildone', 'marilou.jacildone@softvision.com', '2019-11-04', 5, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(946269, 'Suyat', 'Matk Kenneth', 'S', 'Matk Kenneth Suyat', 'markkenneth.suyat@softvision.com', '2020-04-01', 5, 7, 9, 6, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(948940, 'Ligsay', 'Randu', 'S', 'Randu Ligsay', 'randy.ligsay@softvision.com', '2021-06-23', 5, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945401, 'Canada', 'Regine', 'S', 'Regine Canada', 'regie.canada@softvision.com', '2021-05-15', 5, 7, 9, 3, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(950512, 'Rojas', 'Francis', 'S', 'Francis Rojas', 'rojas.francis@softvision.com', '2019-02-23', 5, 7, 9, 7, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(947135, 'Arboleda', 'Rolan', 'S', 'Rolan Arboleda', 'rolan.arboleda@softvision.com', '2020-01-07', 5, 7, 9, 5, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(945511, 'Casares', 'Kenneth', 'S', 'Kenneth Casares', 'kenneth.casares@softvision.com', '2017-12-12', 5, 7, 9, 1, true, false);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES(942812, 'Garcia ', 'Paulo', 'S', 'Paulo Garcia ', 'paulo.garcia2@softvision.com', '2021-08-14', 5, 7, 9, 1, true, false);

-- INSERT INTO PEOPLEDETAILS 

-- INSERT INTO PEOPLEDETAILSDESC
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Bench Tags', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('GoP Account', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Expectation Setting Meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Signed Expectation Setting Document', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Monthly Touchpoint Introduction Email', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Performance Evaluation recurring meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Included in Community Communications', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('GoP Instruction Email', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('2nd Month Touchpoint Meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('3rd Month Performance Evaluation received from Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('3rd Month Touchpoint Performance Evaluation Request to Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('3rd Month Touchpoint Meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('4th Month Touchpoint Mtg', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('5th Month Touchpoint Performance Evaluation Request to Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('5th Month Performance Evaluation received from Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('5th Month Touchpoint Meeting', true);

-- INSERT INTO  PEOPLEPRIMARYSKILLS
-- INSERT INTO PEOPLESKILLS
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('.Net', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('.NET Core', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('.NET Framework', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ADB', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ADF', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ADLS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Agile', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('AJAX', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Algorithms', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Amazon Web', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Analytical Skills', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Analytics', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Android', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Android/Ios Software Development Kit', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Android/Ios Ux And Ui', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Angular', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Angular.Js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('API', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Artifical Intelligence', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ASP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ASP.NET', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('AWS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Azure', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Azure DevOps', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('BI', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Big Data', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Bigcommerce', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Blazor', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Bootstrap', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('C', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('C#', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('C++', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Calculating', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Ceh', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Cisa', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Cloud', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Cloud Security', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Compiling Statistics', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Computing', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('CSS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Analysis', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Analytics', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data And File Encryption.', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Cube Technology', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Engineering', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Mining', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Quality', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Queries', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Science', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Structures And Algorithms', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Visualization', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Database', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Database Design', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Database Management', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('DevOps', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Docker', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Documentation', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Dynamics', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Flutter', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Full Stack', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Full Stack ', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Full Stack .NET', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Gcih', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('GCP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Github', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Google Cloud', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('GraphQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('gRPC', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('HTML', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Html5', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('IaC', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('InfoSec', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Integration', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Interface', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Intrusion Detection', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Ios', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Java', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Javascript', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('jQuery', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('jQuery ', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kamatera', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kendo', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kubernetes', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Ladder', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('LESS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Linux', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('M365', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Machine Learning', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Magento', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Malware Analysis', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Masos', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MAUI', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MERN', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Microservices', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ML.NET', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Mobile', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Modeling', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Modification', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MongoDB', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MS BI Stack', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MSSQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MVC', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MVVM', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MySQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Needs Analysis', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Network Security', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Node.js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('NoSQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('NUnit', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Olap', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('OOP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Opencart', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Oracle', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Oscp', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Php', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Platform', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PostgreSQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Power Automate', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PowerBI', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Python', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Quantitative Reports', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Quantitative Research', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('R', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Raw Data Processing And Integration', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Razor', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('React', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('React.Js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ReactJS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Redshift', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Report Builder', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('REST', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Root Cause Analysis', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Roslyn', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Ruby', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SAP Crystal Reports', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SAP Web Intelligence', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SAS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Scrum', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Secude Code Development', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Server', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Serverless', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Services', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SharePoint', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Shopify', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SignalR', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Snowflakes', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SPARK', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Springboot', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SSAS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SSIS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SSRS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Statistical Analysis', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Tableau', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Typescript', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('User', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('UWP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Visual Studio', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Vue.Js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('WebAssembly', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Webforms', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Windows', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Woocommerce', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('WPF', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Xamarin', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Xcode Development', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('XUnit', true);

-- INSERT INTO peopletechnicalinterest 
-- INSERT INTO project
INSERT INTO public.project (projectdesc, isactive) VALUES('Magenic PDP Bench', True);
INSERT INTO public.project (projectdesc, isactive) VALUES('ATI', True);
INSERT INTO public.project (projectdesc, isactive) VALUES('Earnst & Young', True);
INSERT INTO public.project (projectdesc, isactive) VALUES('Fiserv', True);
INSERT INTO public.project (projectdesc, isactive) VALUES('Warner Music Group', True);
INSERT INTO public.project (projectdesc, isactive) VALUES('Merchants Fleet', True);
INSERT INTO public.project (projectdesc, isactive) VALUES('Toyota', True);

-- INSERT INTO workstate 
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('1st Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('2nd Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('3rd Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('4th Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('5th Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('Onboarding', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('Regular', TRUE);


