-- INSERT INTO COMMUNITY
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Enterprise .NET','', 6, 'Enterprise .NET Community leverages the combined community knowledge using .NET Core and .NET 5, as well as tools and frameworks to deliver excellent quality for our partners.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Full-stack Web','', 10, 'Full-Stack Web are expert ib front-end frameworks and NODE.Js frameworks',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Quality Engineering','', 8, 'Quality Engineering covers many domains regarding types of testing including smoke, regression, user acceptance, unit, sanity, system, component, and integration.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Cloud and DevOps','', 6, 'Cloud and DevOps community work with many different clients, and there are no two identical projects, especially from a DevOps perspective, which means our community gets to flex their knowledge in surprising ways.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Big Data & Analytics','', 6, 'Big Data and Analytics community are passionate about data and experts on Big Data Engineering, Reporting, Business Intelligence, or Database Development & Administration.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Enterprise Coffee','', 9, 'Enterprise Coffee community are expert from running projects in the AWS cloud, or utilizing S3, EC2, RDS, SQS and Lambdas, to coding in Git, or using MVC.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Mobile Cross Platform','', 9, 'Cross mobile plat.form community c.omposed of teams of Web developers, Android developers, iOS developers',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Research and Development','', 10, 'Research and Development community are responsible for the upskilling the resources and developing their technical skills.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Product Delivery','', 6, 'Product Delivery ensures an efficient project allocation mechanism to respond quickly to project/customer expectations with the right people.',TRUE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Product Strategy','', 0, 'Product Strategy Community',FALSE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Experience Design','', 0, 'Experience Design Community',FALSE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Artifical Intelligence','', 0, 'Artifical Intelligence Community',FALSE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('IOS','', 0, 'IOS Community',FALSE);
INSERT INTO public.community (communityname, communityicon, communitymgrid, communitydesc, isactive) VALUES ('Android','', 0, 'Android Community',FALSE);

-- INSERT INTO communityadminandmanager
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Administrator 1','admin1@softvision.com','admin1','admin1','admin',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Administrator 2','admin2@softvision.com','admin2','admin2','admin',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Administrator 3','admin3@softvision.com','admin3','admin3','admin',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Administrator 4','admin4@softvision.com','admin4','admin4','admin',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Administrator 5','admin5@softvision.com','admin5','admin5','admin',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Lloyd Joseph Miguel','lloydjoseph.miguel@softvision.com','admin6','admin6','manager',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Gilberto Bernardo Morales','gilbertobernardo.morales@softvision.com','admin7','admin7','manager',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Rennor Galicia','rennor.galicia@softvision.com','admin8','admin8','manager',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Florante Navaja','florante.navaja@softvision.com','admin9','admin9','manager',TRUE);
INSERT INTO public.communityadminandmanager (communityadminandmanagername, csvemail, cognizantid, password, roletype, isactive) VALUES ('Baron Paredes','baronpatrick.paredes@softvision.com','admin10','admin10','manager',TRUE);

-- INSERT INTO JOBLEVEL
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Community Director', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Community Manager', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Regional Solutions Architect', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Solutions Architect', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Principal Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Lead Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Associate Lead Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Senior Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Developer', TRUE);
INSERT INTO public.joblevel(jobleveldesc, isactive) VALUES('Undefined', TRUE);


-- INSERT INTO project
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('MagenicPDPBench', 'MDP-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('AlaskaAirlines-MobileExperience', 'AAME-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('CLA-AIS', 'CLA-AIS-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('CLA-QA', 'CLA-QA-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('Broadridge-AdvisorWorkstation', 'BAW-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('CroweHorwath-Insight', 'CHI-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('GoP_MerchantsFleet-StrategicTeamSupport', 'GMFSTS-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('MerchantsFleetStrategicEnhancementsTeam', 'MFSET-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('CSV_BoiseCascade', 'CSVBS-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('DellOnline-AuthNExperienceTeam', 'DOAET-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('DeltaDental-eBillPayApplnModernization', 'DDEBPAM-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('Discover-PVSAuthUser', 'DPVSAU-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('EYMobilityTax-PeritoMoreno', 'EYMTPM-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('EYMobilityTax-TeamGreatPyramid', 'EYMTTGP-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('Fiserv-DigitalChannelsMobile', 'FDCM-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('FleetResponse-ApplicationSupport', 'FRAS-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('HiSeis-Epicentre', 'HSE-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('LMCORPFinPOD', 'LIP-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('MerchantsFleet-OrderManagement', 'MFO-101', True);
INSERT INTO public.project (projectdesc, projectcode, isactive) VALUES('TraneTechnologies', 'TRT-101', True);


-- INSERT INTO workstate 
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('1st Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('2nd Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('3rd Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('4th Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('5th Month', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('Onboarding', TRUE);
INSERT INTO public.workstate(workstatedescription, isactive)VALUES('Regular', TRUE);

-- INSERT INTO public.people
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tuazon','Mau','','Mau Tuazon','mauriza.tuazon@softvision.com','2017-09-23',7,7,6,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Flores','Bob','','Bob Flores','ronyan.flores@softvision.com','2020-01-19',7,7,7,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'De Los Angeles','Wayne','','Wayne De Los Angeles','wayne.delosangeles@softvision.com','2017-10-18',7,7,6,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Rueda','Paolo','','Paolo Rueda','paolorey.rueda@softvision.com','2019-07-15',7,7,7,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Castro','Allan','','Allan Castro','allan.castro2@softvision.com','2020-12-25',7,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dableo','Arnold','','Arnold Dableo','arnold.dableo@softvision.com','2019-07-10',7,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Natividad','Aura','','Aura Natividad','auracedes.natividad@softvision.com','2021-06-01',7,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Vergara','Christian','','Christian Vergara','christianpaul.vergara@softvision.com','2017-11-01',7,7,9,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Macatangay','Eldrich','','Eldrich Macatangay','eldrich.macatangay@softvision.com','2017-08-29',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dela Pe�a','Hanami','','Hanami Dela Pe�a','hanamiann.delapena@softvision.com','2021-05-01',7,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tandang','Jan Aldrich','','Jan Aldrich Tandang','janaldrich.tandang@softvision.com','2021-09-12',7,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Vallejos','Jayhar','','Jayhar Vallejos','jayhar.vallejos@softvision.com','2019-12-17',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Silvestre','Jerome','','Jerome Silvestre','jerome.silvestre@softvision.com','2021-04-11',7,7,8,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Corpuz','Jim','','Jim Corpuz','janianmichael.corpuz@softvision.com','2020-11-02',7,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Balbarona','Jojo','','Jojo Balbarona','jojo.balbarona@softvision.com','2018-01-14',7,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Serrano','Joseph','','Joseph Serrano','josephdavid.serrano@softvision.com','2017-05-07',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gloria','Josha','','Josha Gloria','joshuamiguel.gloria@softvision.com','2019-07-11',7,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Boado','Justin','','Justin Boado','justinbernard.boado@softvision.com','2017-06-28',7,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cautiverio','Loyd','','Loyd Cautiverio','loydzedric.cautiverio@softvision.com','2017-06-07',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Pe�ano','Marc','','Marc Pe�ano','marcdominic.penano@softvision.com','2021-04-25',7,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Obog','Mario','','Mario Obog','marionino.obog@softvision.com','2020-04-07',7,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Abrazado','Nikko','','Nikko Abrazado','nikkopaulo.abrazado@softvision.com','2017-10-27',7,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cayetano','Ni�o','','Ni�o Cayetano','ninobenedict.cayetano@softvision.com','2017-03-10',7,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Daza','Olive','','Olive Daza','olive.daza@softvision.com','2017-09-15',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Eliseo','Pauline','','Pauline Eliseo','paulinejoena.eliseo@softvision.com','2019-02-20',7,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Maquinto','Jan Philipp','','Jan Philipp Maquinto','janphilipp.maquinto@softvision.com','2018-09-25',7,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Lipardo','Roi','','Roi Lipardo','roijesson.lipardo@softvision.com','2018-10-09',7,7,9,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Orobia','Runette','','Runette Orobia','runettenicole.orobia@softvision.com','2020-12-30',7,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gonzales','Warren','','Warren Gonzales','warren.gonzales@softvision.com','2017-10-10',7,7,9,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Decena','Zaldy','','Zaldy Decena','rizaldy.decena@softvision.com','2017-11-10',7,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gonzales','Alvin','','Alvin Gonzales','alvin.gonzales@softvision.com','2020-10-01',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Evangelista','Miah','','Miah Evangelista','jeremiah.evangelista@softvision.com','2018-12-31',7,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Mantaring','Rod','','Rod Mantaring','jamesrod.mantaring@softvision.com','2021-05-26',7,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gomez','Jerymy','','Jerymy Gomez','jerymy.gomez@softvision.com','2017-12-10',7,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Suan','Jayson','','Jayson Suan','jayson.suan@softvision.com','2020-04-22',7,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Hagos','Stevania','','Stevania Hagos','stevaniaallison.h@softvision.com','2019-04-29',7,7,9,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Perez','Christian','','Christian Perez','christian.perez@softvision.com','2020-03-22',7,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Macandili','Aaron','','Aaron Macandili','aaron.macandili@softvision.com','2021-10-18',7,7,7,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Alcachupas','Charles','','Charles Alcachupas','charles.alcachupas@softvision.com','2019-04-14',7,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Felix','Tonette','','Tonette Felix','mariaantoinette.f@softvision.com','2017-06-13',7,7,9,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Villanueva','Jophiel','','Jophiel Villanueva','jophiel.villanueva@softvision.com','2021-03-30',7,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Morales','John','','John Morales','john.morales@softvision.com','2020-02-04',7,7,7,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Mariano','Jhan Jerico','','Jhan Jerico Mariano','jhanjericho.mariano@softvision.com','2017-03-26',7,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dela Cruz','Rozen','','Rozen Dela Cruz','rozen.delacruz@softvision.com','2018-12-30',7,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Escaro','Kevin','','Kevin Escaro','kevin.escaro@softvision.com','2017-11-30',7,7,9,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Estrada','Gerald','','Gerald Estrada','gerald.estrada@softvision.com','2021-04-02',7,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Catipon','Mary Allen','','Mary Allen Catipon','allen.catipon@softvision.com','2021-09-11',7,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dela Cruz','Michael','','Michael Dela Cruz','michael.delacruz@softvision.com','2021-02-03',7,7,9,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gealogo','Joemar','','Joemar Gealogo','joemar.gealogo@softvision.com','2017-09-07',7,7,7,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Limosenero','Rey','','Rey Limosenero','rey.limosenero@softvision.com','2017-09-10',7,7,7,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Grezola','Reyzald','','Reyzald Grezola','reyzald.grezola@softvision.com','2019-04-09',7,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Legaspi','Mary Allen','','Mary Allen Legaspi','maryanne.legaspi@softvision.com','2018-10-01',7,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dela Torre','Joseph','','Joseph Dela Torre','joseph.delatorre@softvision.com','2019-03-15',7,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Celis','Dax','','Dax Celis','daxgabriel.celis@softvision.com','2020-05-30',8,7,7,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cruz','Lyndon','','Lyndon Cruz','lyndon.cruz@softvision.com','2019-03-26',8,7,6,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cariaga','Hermoso','','Hermoso Cariaga','hermoso.cariaga@softvision.com','2018-03-30',8,7,7,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tayabas','Anthony','','Anthony Tayabas','anthonymark.tayabas@softvision.com','2021-09-06',8,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Castro','Allan ','','Allan  Castro','allan.castro2@softvision.com','2017-02-03',8,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Villaflor','Mac Mac','','Mac Mac Villaflor','markjoseph.villaflor@softvision.com','2017-09-27',8,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Sarmiento','Michael','','Michael Sarmiento','michael.sarmiento@softvision.com','2019-05-18',8,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Mosca','Neil','','Neil Mosca','neilnicoli.mosca@softvision.com','2021-02-05',8,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Mu�oz','Rica','','Rica Mu�oz','rica.munoz@softvision.com','2020-01-04',8,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Ulep','Robert','','Robert Ulep','robert.ulep@softvision.com','2020-09-20',8,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Roman','Tobby','','Tobby Roman','tobyrodin.roman@softvision.com','2019-08-23',8,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Clemente','Faye','','Faye Clemente','cecilfaye.clemente@softvision.com','2020-09-12',8,7,9,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tuazon','Harvy','','Harvy Tuazon','harvy.tuazon@softvision.com','2020-12-05',8,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Bocobo','Rhoderick','','Rhoderick Bocobo','rhoderick.bocobo@softvision.com','2020-09-02',8,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Aguado','John Joseph','','John Joseph Aguado','johnjoseph.aguado@softvision.com','2020-11-11',8,7,6,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dela Rosa','Gian','','Gian Dela Rosa','gianroni.delarosa@softvision.com','2019-04-06',8,7,9,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Dumagat','Johnny','','Johnny Dumagat','johnny.dumagat@softvision.com','2019-07-05',8,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Flores','Randy','','Randy Flores','randy.flores@softvision.com','2020-08-17',8,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2090874,'Villegas','Douie Villegas','','Douie Villegas Villegas','douienino.villegas@softvision.com','2018-02-28',4,7,9,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933568,'Barrientos','Elther Barrientos','','Elther Barrientos Barrientos','elther.barrientos@softvision.com','2019-07-09',4,7,7,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2022764,'Sunpongco II','Herminigildo','','Herminigildo Sunpongco II','herminigildo.sunpongco@softvision.com','2020-11-18',4,7,7,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Acido','Jayveelyn','','Jayveelyn Acido','jayveelyn.acido@softvision.com','2020-01-11',4,7,7,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gallego','John Kenneth','','John Kenneth Gallego','johnkenneth.gallego@softvision.com','2017-07-19',4,7,8,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Matela','Lorenzo Alexander','','Lorenzo Alexander Matela','lorenzoalexander.matela@softvision.com','2021-01-22',4,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933586,'Budy','Maryjoy','','Maryjoy Budy','maryjoy.budy@softvision.com','2017-02-27',4,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Manalo','Michael','','Michael Manalo','michael.manalo@softvision.com','2019-11-02',4,7,9,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tapon','Paul Evangel','','Paul Evangel Tapon','paulevangel.tapon@softvision.com','2021-05-03',4,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933684,'Gollayan','Raffie','','Raffie Gollayan','raffie.gollayan@softvision.com','2017-01-21',4,7,6,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Hernandez','Ron','','Ron Hernandez','ron.hernandez@softvision.com','2018-12-15',4,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933581,'Borlongan','Ted','','Ted Borlongan','ted.borlongan@softvision.com','2017-11-16',4,7,4,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933903,'Uy','Tyrone Rodney','','Tyrone Rodney Uy','tyronerodney.uy@softvision.com','2017-05-08',4,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Zabala','Zackary','','Zackary Zabala','zackary.zabala@softvision.com','2019-07-17',4,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2107746,'Macapagal','Aaron','','Aaron Macapagal','aaron.macapagal@softvision.com','2021-04-08',1,7,7,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933608,'Carandang Jr','Alberto','','Alberto Carandang Jr','alberto.carandang@softvision.com','2018-09-16',1,7,7,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Sala�o','Alfie','','Alfie Sala�o','alfie.salano@softvision.com','2018-11-13',1,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2025237,'Pajaret','Alfredo James','','Alfredo James Pajaret','alfredojames.pajaret@softvision.com','2020-08-06',1,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cadiz','Aljon Rey','','Aljon Rey Cadiz','aljonrey.cadiz@softvision.com','2019-10-01',1,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933889,'Tolentino','Allan','','Allan Tolentino','allanjay.tolentino@softvision.com','2018-12-13',1,7,7,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2089233,'Lopez','Allan','','Allan Lopez','allankarl.lopez@softvision.com','2020-07-02',1,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tolentino','Alter','','Alter Tolentino','alternodalo.tolentino@softvision.com','2017-02-28',1,7,6,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933664,'Espinosa','Alvin','','Alvin Espinosa','alvin.espinosa@softvision.com','2018-08-10',1,7,8,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2055538,'Santelices','Andrew','','Andrew Santelices','andrew.santelices@softvision.com','2017-06-11',1,7,9,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Manalili','Angelo','','Angelo Manalili','angelo.manalili@softvision.com','2017-09-07',1,7,7,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933696,'Herana','Angelo','','Angelo Herana','angeloemmanuel.herana@softvision.com','2019-07-13',1,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933921,'Anonas','Anthony','','Anthony Anonas','anthony.anonas@softvision.com','2021-02-09',1,7,7,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Lopez','Armando','','Armando Lopez','armando.lopez@softvision.com','2020-04-14',1,7,6,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Parulan','Benedick','','Benedick Parulan','benedick.parulan@softvision.com','2018-10-29',1,7,3,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933589,'Buluran','Benjamin','','Benjamin Buluran','benjamin.buluran@softvision.com','2021-07-06',1,7,7,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933764,'Manalo','Benjie','','Benjie Manalo','benjie.manalo@softvision.com','2017-03-02',1,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933591,'Berns','Caay','','Caay Berns','bernardvic.caay@softvision.com','2019-01-24',1,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2163192,'Yap','Angela Bianca','','Angela Bianca Yap','biancaangela.yap@softvision.com','2018-12-30',1,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2111760,'Ogerio','Bien Liomar','','Bien Liomar Ogerio','bienliomar.ogerio@softvision.com','2019-05-30',1,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (937631,'Guevarra','Benjo','','Benjo Guevarra','bienvenido.guevarra@softvision.com','2017-04-11',1,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Malbataan','Billy','','Billy Malbataan','billy.malbataan@softvision.com','2021-09-18',1,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tiamsic','Bob','','Bob Tiamsic','bobjason.tiamsic@softvision.com','2017-07-02',1,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2111753,'Baldos','Brian','','Brian Baldos','brian.baldos@softvision.com','2018-05-04',1,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933551,'Arabejo','Bryan','','Bryan Arabejo','bryan.arabejo@softvision.com','2018-09-22',1,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2169638,'Feliciano','Bryantt','','Bryantt Feliciano','bryantt.feliciano@softvision.com','2021-04-09',1,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933619,'Cerbo','Chen','','Chen Cerbo','cheneil.cerbo@softvision.com','2019-07-25',1,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Abejuro','Christian','','Christian Abejuro','cheneil.cerbo@softvision.com','2021-02-13',1,7,9,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2124889,'Sarzaba','Christian','','Christian Sarzaba','christian.sarzaba@softvision.com','2017-09-22',1,7,9,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Palisoc','Christopher','','Christopher Palisoc','christopher.palisoc@softvision.com','2018-03-13',1,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tubig','Christopher','','Christopher Tubig','christopher.palisoc@softvision.com','2018-05-23',1,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Ferrolino','Clyde Bryan','','Clyde Bryan Ferrolino','clydebryan.ferrolino@softvision.com','2020-04-07',1,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Zamoranos','Coleen Ann','','Coleen Ann Zamoranos','coleenann.zamoranos@softvision.com','2020-02-15',1,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2176512,'Dela Cuz','Denzel Eriz','','Denzel Eriz Dela Cuz','denzeleriz.delacruz@softvision.com','2017-05-30',1,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Valderama','Derick','','Derick Valderama','derrick.valderama@softvision.com','2021-06-10',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933538,'Aguirre','Edsel','','Edsel Aguirre','edsel.aguirre@softvision.com','2019-05-23',1,7,8,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933572,'Bayno','Edu','','Edu Bayno','eduardo.bayno@softvision.com','2019-07-03',1,7,9,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933788,'Edwin','Moncayo','','Moncayo Edwin','edwin.moncayo@softvision.com','2020-03-06',1,7,6,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2107749,'Torres','Emmanuel Andrew','','Emmanuel Andrew Torres','emmanuelandrew.t@softvision.com','2018-08-22',1,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933607,'Caraan','Eric','','Eric Caraan','eric.caraan@softvision.com','2017-05-03',1,7,6,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933609,'Cari�o','Erich','','Erich Cari�o','erich.carino@softvision.com','2018-01-15',1,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Emmanuel','Erin','','Erin Emmanuel','erinemmanuel.paca@softvision.com','2017-09-19',1,7,7,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2148851,'Lirazan','Erwin','','Erwin Lirazan','erwinlirazan.daza@softvision.com','2019-03-11',1,7,9,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933839,'Reyes III','Rex','','Rex Reyes III','exequiel.reyes@softvision.com','2019-02-05',1,7,8,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'De Guzman','Fernando','','Fernando De Guzman','fernando.deguzman@softvision.com','2017-03-13',1,7,7,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Jon','Yago','','Yago Jon','fernando.yago@softvision.com','2019-06-05',1,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933882,'Tacata','Francis','','Francis Tacata','francisantonio.tacata@softvision.com','2018-11-29',1,7,6,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933863,'Sandico','Bullet','','Bullet Sandico','francisbullet.sandico@softvision.com','2017-05-28',1,7,6,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Ala','Francis','','Francis Ala','francisjoegennee.ala@softvision.com','2018-12-16',1,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2115929,'Compa�ado','Franklin','','Franklin Compa�ado','franklin.companado@softvision.com','2021-05-10',1,7,9,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933599,'Calica','Gabriel Angelo','','Gabriel Angelo Calica','gabrielangelo.calica@softvision.com','2020-09-08',1,7,9,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933620,'Ceredon','Gen','','Gen Ceredon','gennesisjoy.ceredon@softvision.com','2018-01-07',1,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Gono','Gerald','','Gerald Gono','gerald.gono@softvision.com','2019-09-03',1,7,7,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933583,'Bragais','Bimz','','Bimz Bragais','gerardgil.bragais@softvision.com','2020-02-18',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933855,'Salaritan','Gian','','Gian Salaritan','gian.salaritan@softvision.com','2018-12-17',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2031614,'Daria','Giancarlo','','Giancarlo Daria','giancarlo.daria@softvision.com','2017-06-08',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2133504,'Capiral','Hans Gustaf','','Hans Gustaf Capiral','hansgustaf.capiral@softvision.com','2021-01-15',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Oliver','Herbert','','Herbert Oliver','','2021-08-31',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933546,'Amaro','Herman','','Herman Amaro','herman.amaro@softvision.com','2018-04-22',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (937642,'Alcaraz','James','','James Alcaraz','james.alcaraz@softvision.com','2017-07-13',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cusi','James Philip','','James Philip Cusi','jamesphilip.cusi@softvision.com','2018-07-28',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933610,'Carlos','JR','','JR Carlos','jamesrellie.carlos@softvision.com','2017-10-22',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Jan Mark','Bernales','','Bernales Jan Mark','janmark.bernales@softvision.com','2017-09-30',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Paredes','Janniele','','Janniele Paredes','janniele.paredes@softvision.com','2019-06-03',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Laguardia','Janzelle','','Janzelle Laguardia','janzelle.laguardia@softvision.com','2020-06-30',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933616,'Cayetano','Jed','','Jed Cayetano','jed.cayetano@softvision.com','2021-02-28',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933543,'Alfaro','Jefferson','','Jefferson Alfaro','jefferson.alfaro@softvision.com','2017-06-06',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Acosta ','Jerffret','','Jerffret Acosta ','jeffrey.acosta@softvision.com','2018-05-06',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933836,'Reverente','Jeffrey','','Jeffrey Reverente','jeffreypaolo.reverente@softvision.com','2020-04-22',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Reyes','Jeffrey','','Jeffrey Reyes','jesper.reyes@softvision.com','2020-05-13',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2114504,'Castro','Jesse','','Jesse Castro','jesse.castro@softvision.com','2020-02-25',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2041507,'Rykiel','Joel','','Joel Rykiel','joelrykiel.ng@softvision.com','2018-10-05',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933566,'Banania','Joey','','Joey Banania','joey.banania@softvision.com','2021-01-02',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2069339,'Allen','John','','John Allen','johnallen.fortes@softvision.com','2021-08-12',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933647,'Decena','Dave','','Dave Decena','johndave.decena@softvision.com','2019-08-14',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933701,'Infante','Dave','','Dave Infante','johndave.infante@softvision.com','2017-12-18',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tugado','John Ephraim','','John Ephraim Tugado','johnephraim.tugado@softvision.com','2017-05-24',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2133509,'Rimorin','John Jay','','John Jay Rimorin','johnjay.rimorin@softvision.com','2018-03-27',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933683,'Go','Kevin','','Kevin Go','johnkevin.go@softvision.com','2018-02-17',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Bersonda','John Patrick','','John Patrick Bersonda','johnpatrick.bersonda@softvision.com','2020-10-21',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Lazaro','John Paul','','John Paul Lazaro','johnpaul.lazaro@softvision.com','2017-07-12',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933549,'Ang','John Rafael','','John Rafael Ang','johnrafael.ang@softvision.com','2018-04-01',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2124888,'Orale','John Raymer','','John Raymer Orale','johnraymer.orale@softvision.com','2019-12-21',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Malabanan','John Richard','','John Richard Malabanan','johnrichard.malabanan@softvision.com','2018-08-07',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933886,'Taruc','Jommel','','Jommel Taruc','johnrommel.taruc@softvision.com','2019-06-05',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933635,'Custodio','John Wendell','','John Wendell Custodio','johnwendell.custodio@softvision.com','2020-05-22',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933704,'Jacob','Jonathan','','Jonathan Jacob','jonathan.jacob@softvision.com','2021-01-15',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Aguisanda','Jonnalyn','','Jonnalyn Aguisanda','jonnalyn.aguisanda@softvision.com','2020-04-03',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Molato','Jorelangelo','','Jorelangelo Molato','jorelangelo.molato@softvision.com','2021-06-28',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933831,'Quipanes','Jose Marlon','','Jose Marlon Quipanes','josemarlon.quipanes@softvision.com','2018-04-13',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Manangan','Joseph','','Joseph Manangan','joseph.manangan@softvision.com','2021-03-20',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Sanchez','Chard','','Chard Sanchez','josericardo.sanchez@softvision.com','2018-12-22',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Tuazon','Joshua James','','Joshua James Tuazon','joshuajames.tuazon@softvision.com','2020-09-21',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933575,'Blanco','Jovan','','Jovan Blanco','jovan.blanco@softvision.com','2018-10-19',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Roxas','Juan Gabriel','','Juan Gabriel Roxas','juangabriel.roxas@softvision.com','2017-02-18',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'De Castro','Julius Matthew','','Julius Matthew De Castro','juliusmatthew.decastro@softvision.com','2018-07-14',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Belleza','Julius Miguel','','Julius Miguel Belleza','juliusmiguel.belleza@softvision.com','2017-01-04',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933799,'Nicolas','Julius','','Julius Nicolas','juliusoliver.nicolas@softvision.com','2020-08-07',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Montalban','Justin','','Justin Montalban','justinjoseph.montalban@softvision.com','2020-09-09',1,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2169639,'Flamiano','Karen Dale','','Karen Dale Flamiano','karen.daleflamiano@softvision.com','2017-03-18',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2098727,'Lopez','Karenina','','Karenina Lopez','karenina.lopez@softvision.com','2019-10-26',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Nuguid','Karen Mae','','Karen Mae Nuguid','karenmae.nuguid@softvision.com','2019-01-15',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Canet','Kenneth','','Kenneth Canet','kenneth.canet@softvision.com','2020-02-19',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Cainday','Kevin','','Kevin Cainday','kevinporferio.cainday@softvision.com','2020-01-17',1,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Vendiola','Kim','','Kim Vendiola','kimberlyanne.vendiola@softvision.com','2020-10-04',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2148861,'Ramos','Kirstin Megga','','Kirstin Megga Ramos','kirstinmegga.ramos@softvision.com','2018-04-18',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2124887,'Cadalzo','Lambert','','Lambert Cadalzo','lambert.cadalzo@softvision.com','2020-08-03',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2095145,'Mabugay','Louie Gie','','Louie Gie Mabugay','louiegie.mabugay@softvision.com','2021-01-02',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Estigoy','Marc Joemar','','Marc Joemar Estigoy','mariatheresa.payong@softvision.com','2021-07-09',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2031617,'Payong','Maria Theresa','','Maria Theresa Payong','mariatheresa.payong@softvision.com','2019-09-07',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933858,'Sales','Mavie','','Mavie Sales','marjlevy.sales@softvision.com','2020-04-02',1,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Villanueva','Mark','','Mark Villanueva','mark.villanueva@softvision.com','2018-04-23',1,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Nayat','Mark Anthony','','Mark Anthony Nayat','markanthony.nayat@softvision.com','2017-01-28',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Soriano','Mark Anthony','','Mark Anthony Soriano','markanthony.soriano@softvision.com','2017-03-02',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Agrimano','Jerome','','Jerome Agrimano','markjerome.agrimano@softvision.com','2017-03-31',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933803,'Ong','Lorenz','','Lorenz Ong','marklorenz.ong@softvision.com','2018-05-13',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933926,'Elpedes','Marlon','','Marlon Elpedes','marlon.elpedes@softvision.com','2018-05-18',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Briones','Marvin','','Marvin Briones','marvin.briones@softvision.com','2021-03-13',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2107750,'Vicedo','Maxinne','','Maxinne Vicedo','maxinne.vicedo@softvision.com','2017-05-08',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Hernanadex','Michael Ivan','','Michael Ivan Hernanadex','michaelivan.hernandez@softvision.com','2020-07-08',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2023160,'Vincent','Mikhail','','Mikhail Vincent','mikhailvincent.malenab@softvision.com','2017-01-24',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Andre','Neil','','Neil Andre','neilandre.tongco@softvision.com','2017-05-05',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2124890,'Solitana','Nico','','Nico Solitana','nico.solitana@softvision.com','2017-05-15',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933807,'Oriarte','Norben','','Norben Oriarte','norben.oriarte@softvision.com','2017-07-09',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933834,'Ramos','Raymarc','','Raymarc Ramos','raymarc.ramos@softvision.com','2017-09-19',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Flores','Raymart','','Raymart Flores','raymart.flores@softvision.com','2021-04-06',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933646,'De','Remar','','Remar De','remarzebedee.devera@softvision.com','2019-05-15',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Rodriguez','Reycie','','Reycie Rodriguez','reycie.rodriguez@softvision.com','2021-07-20',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933534,'Adonay','Reynner','','Reynner Adonay','reynner.adonay@softvision.com','2017-04-17',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Bonion','Rhenier','','Rhenier Bonion','rhenier.bonion@softvision.com','2019-08-20',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933935,'Calingan','Jek','','Jek Calingan','ricardo.calingan@softvision.com','2020-07-24',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933691,'Jr.,','Rodrigo','','Rodrigo Jr.,','rodrigo.gonzales@softvision.com','2019-01-28',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2120451,'John','Romel','','Romel John','romeljohn.monsanto@softvision.com','2017-08-14',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Alfred','Ron','','Ron Alfred','ronalfred.natividad@softvision.com','2017-01-04',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2133508,'Osinsao','Rosemarie','','Rosemarie Osinsao','rosemarie.osinsao@softvision.com','2020-06-25',1,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (942321,'Rubin','Ryan','','Ryan Rubin','ryan.rubin@softvision.com','2019-12-27',1,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Aguilos','Samuel Marvin','','Samuel Marvin Aguilos','samuelmarvin.aguilos@softvision.com','2021-06-26',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Enriquez','Sean','','Sean Enriquez','sean.enriquez@softvision.com','2020-04-07',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933587,'Buenaventura','Sidney','','Sidney Buenaventura','sidney.buenaventura@softvision.com','2017-05-09',1,7,10,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933740,'Malabonga','Ted Nico','','Ted Nico Malabonga','TedNico.Malabonga@softvision.com','2018-02-17',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2072654,'Paulo','Van','','Van Paulo','vanpaulo.fernandez@softvision.com','2018-07-22',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933571,'Basco','Victorian','','Victorian Basco','victorian.bascos@softvision.com','2019-12-04',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Wilfred','Dugang','','Dugang Wilfred','wilfrednyan.dugang@softvision.com','2017-10-30',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933733,'Macatangay','Wilson','','Wilson Macatangay','wilson.macatangay@softvision.com','2020-11-04',1,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2183601,'Dela Rosa','Mark Jun D','','Mark Jun D Dela Rosa','markjun.delarosa@softvision.com','2021-03-14',1,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Ursua Jr','Edgar','','Edgar Ursua Jr','edgar.ursua@softvision.com','2019-09-26',1,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Richohermoso','Jerome','','Jerome Richohermoso','jerome.ricohermoso@softvision.com','2018-10-17',1,7,10,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933909,'Valle','An Konim','','An Konim Valle','ankonim.valle@softvision.com','2018-02-01',5,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (940538,'Bungabong','Anthony','','Anthony Bungabong','anthony.bungabong@softvision.com','2018-12-07',5,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933631,'Costales','Catherine Jean','','Catherine Jean Costales','catherinejean.costales@softvision.com','2019-03-09',5,7,10,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933892,'Tolete','Dustine','','Dustine Tolete','dustine.tolete@softvision.com','2017-11-26',5,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933565,'Balmonte','J Martin','','J Martin Balmonte','jmartin.balmonte@softvision.com','2017-10-22',5,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933032,'Abello','John Dennis','','John Dennis Abello','johndennis.abello@softvision.com','2018-12-27',5,7,10,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Larida','John Paul','','John Paul Larida','johnpaul.larida@softvision.com','2018-07-18',5,7,10,4,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933606,'Capucion','Joyce Anne','','Joyce Anne Capucion','joyceanne.capucion@softvision.com','2019-08-28',5,7,10,2,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933700,'Igrobay','Julie Pay','','Julie Pay Igrobay','juliemae.igrobay@softvision.com','2018-12-10',5,7,10,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Magsino','June Lester ','','June Lester  Magsino','junellnino.magsino@softvision.com','2018-06-15',5,7,10,6,FALSE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Ancisto','Lester','','Lester Ancisto','lester.anciro@softvision.com','2019-03-25',5,7,9,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Jacildone','Marilou','','Marilou Jacildone','marilou.jacildone@softvision.com','2019-11-04',5,7,7,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (940541,'Suyat','Matk Kenneth','','Matk Kenneth Suyat','markkenneth.suyat@softvision.com','2020-04-01',5,7,8,6,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (933718,'Ligsay','Randu','','Randu Ligsay','randy.ligsay@softvision.com','2021-06-23',5,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (947062,'Canada','Regine','','Regine Canada','regie.canada@softvision.com','2021-05-15',5,7,8,3,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (2019213,'Rojas','Francis','','Francis Rojas','rojas.francis@softvision.com','2019-02-23',5,7,9,7,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (0,'Arboleda','Rolan','','Rolan Arboleda','rolan.arboleda@softvision.com','2020-01-07',5,7,8,5,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (944527,'Casares','Kenneth','','Kenneth Casares','kenneth.casares@softvision.com','2017-12-12',5,7,8,1,TRUE,FALSE);
INSERT INTO public.people (cognizantid, lastname, firstname, middlename, fullname, csvemail, hireddate, communityid, workstateid, joblevelid, projectid, isactive, isprobationary) VALUES (947065,'Garcia ','Paulo','','Paulo Garcia ','paulo.garcia2@softvision.com','2021-08-14',5,7,9,1,TRUE,FALSE);


-- INSERT INTO PEOPLEDETAILS (TODO)

-- INSERT INTO PEOPLEDETAILSDESC
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Bench Tags', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('GoP Account', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Expectation Setting Meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Signed Expectation Setting Document', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Monthly Touchpoint Introduction Email', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Performance Evaluation recurring meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('Included in Community Communications', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('GoP Instruction Email', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('2nd Month Touchpoint Meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('3rd Month Performance Evaluation received from Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('3rd Month Touchpoint Performance Evaluation Request to Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('3rd Month Touchpoint Meeting', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('4th Month Touchpoint Mtg', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('5th Month Touchpoint Performance Evaluation Request to Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('5th Month Performance Evaluation received from Project Lead', true);
INSERT INTO public.peopledetailsdesc (peopledetailsdesc, isactive) VALUES('5th Month Touchpoint Meeting', true);

-- INSERT INTO  PEOPLEPRIMARYSKILLS (TODO)
-- INSERT INTO PEOPLESKILLS
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('.NET Core', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('.NET Framework', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ADLS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Agile (Kanban and Scrum)', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Agile Waterfall', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Angular', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Ansible', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Apollo', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Appium', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ASP .NET Web App', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('AWS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('AWS or Azure', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Azure', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Azure DevOps', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Bamboo', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('BeanShell', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('BigQuery', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Blazor', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Bug Tracking: Bugzilla', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('C#', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('C++', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Chef', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('CI/CD: Jenkins', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('CircleCI', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Cypress', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Data Studio', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Databricks', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('DataFactory', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Dataflow', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Docker', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ElasticSearch', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('EmberJS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Entity Framework Core', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Espresso', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ETL:�Glue', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Express.JS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('F#', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('GCP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('gdocs', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Github', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Go Language', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Google Cloud Storage', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('groovy', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Jasmine', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('java', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Java 8 and 11�', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('JavaScript', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Jenkins', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Jest', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Jira', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('JPA / Hibernate', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('JUnit', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('JUnit+B66', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kafka 2 and AWS SQS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kafka 2 and AWS SQS�� messaging�', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kanban', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kinesis', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Koa.JS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('kotlin', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Kubernetes', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Lean', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MariaDB', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Microservices', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ML.NET', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MobX', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Mocha', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MongoDB', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('MySQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Native: in-house libraries', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Nest.JS�� most used Node.JS frameworks', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Network: Axios', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Next.js', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('NgRX', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('NHibernate', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('NUnit', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Oracle', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Oracle��', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Perl�� our �spoken� languages', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PHP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PHPUnit', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PostgreSQL', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PowerBI', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Puppeteer�', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PySpark', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('PyTest', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Python', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Qlik', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Rally', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('React Native Navigation', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('React Navigation', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('ReactJS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Redshift', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Redux', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Redux Sagas', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Redux Thunk', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Remote Desktop Service (MS)', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('RobotFram', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Ruby', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('RxJS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('S3', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SAFe', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SAFe Agile', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Scala', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Scrum', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Scrumban', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Snowflake (the tool', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Spock', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Spring 5�� core platform�', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('SQL Server', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Storybook', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('swift', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Synapse', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Tableau', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Talend', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('TeamCity', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Terraform', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('TestComplete', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('TestLink', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('TestNG', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('TestRail', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('TypeScript', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('UWP', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('VersionOne', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('VirtualBox', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Virtualization: Docker', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('VMware', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('VueJS', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Vuex', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Waterfall', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Web API', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('WebDriver', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('WebDriverIO', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Windows Forms', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('WPF', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Xamarin', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('XCUITest Protractor', true);
INSERT INTO public.peopleskills(peopleskillsdesc, isactive)VALUES('Zephyr', true);


-- INSERT INTO peopletechnicalinterest (TODO)


-- INSERT INTO peopleprimaryskills

INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(1, 1, true);
INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(1, 2, true);
INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(1, 3, true);
INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(2, 1, true);
INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(2, 2, true);
INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(3, 1, true);
INSERT INTO public.peopleprimaryskills (peopleid, peopleskillsid, isactive)VALUES(3, 3, true);
