


### Update
PUT https://localhost:8000/community/cities-update?id=1
Content-Type: application/json
{
  "name": "Mark Doe",
}

PUT https://localhost:8000/community/cities-update/
content-type: application/json

{
    "name": "sample",
}
